version: '3.9'

services:

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORDPRESS_VERSION=$WORDPRESS_VERSION
        - PHP_VERSION=$PHP_VERSION
    links:
      - mysql
    container_name: 'wp-wordpress'
    ports:
      - '$WORDPRESS_PORT:80'
    volumes:
      - '../:/var/www/html/wp-content/plugins/content-pilot'
      - '/var/www/html/wp-content/plugins/content-pilot/node_modules'
      - '/var/www/html/wp-content/plugins/content-pilot/vendor'
    environment:
      WORDPRESS_DB_HOST: mysql:$MYSQL_PORT
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DATABASE
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
      WORDPRESS_DEBUG: 1
      ENV: development

  phpmyadmin:
    links:
      - mysql
    image: 'phpmyadmin:latest'
    container_name: 'wp-pma'
    ports:
      - '$PHPMYADMIN_PORT:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: $MYSQL_PORT
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_ARBITRARY: 1

  mysql:
    image: 'mysql:8.2.0-oracle'
    container_name: 'wp-db'
    ports:
      - '$MYSQL_PORT:3306'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $WORDPRESS_DATABASE
    volumes:
      - '/var/lib/mysql'
