version: '3.9'

# This is only for development purposes.
services:
  mysql:
    image: 'mysql:8.0.31-oracle'
    container_name: 'wp-db'
    ports:
      - '$MYSQL_PORT:3306'
    command: '--default-authentication-plugin=mysql_native_password'
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $WORDPRESS_DATABASE
    volumes:
      - '/var/lib/mysql'

  wordpress:
    links:
      - mysql
    image: 'wordpress:6.1.1-php8.1-apache'
    container_name: 'wp-wordpress'
    ports:
      - '$WORDPRESS_PORT:80'
    volumes:
      - '../:/var/www/html/wp-content/plugins/content-pilot'
      - '/var/www/html/wp-content/plugins/content-pilot/node_modules'
      - '/var/www/html/wp-content/plugins/content-pilot/vendor'
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_NAME: $WORDPRESS_DATABASE
      WORDPRESS_TABLE_PREFIX: $WORDPRESS_TABLE_PREFIX
      WORDPRESS_DEBUG: 1
      ENV: development

  phpmyadmin:
    links:
      - mysql
    image: 'phpmyadmin:5.2.0'
    container_name: 'wp-pma'
    ports:
      - '$PHPMYADMIN_PORT:80'
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: $MYSQL_ROOT_PASSWORD
      PMA_ARBITRARY: 1
